# Generated by Django 5.1.6 on 2025-03-01 17:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_email_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='avatars/default_image_pro.png', max_length=255, verbose_name='image'),
        ),
    ]
